//  Truthy Values 
console.log(Boolean('0'));       // true
console.log(Boolean('8'));       // true
console.log(Boolean('hi'));   // true
console.log(Boolean('Hello'));        // true
console.log(Boolean(10));        // true
console.log(Boolean(42));        // true
console.log(Boolean(7.5)); // true
console.log(Boolean(-20)); // true
console.log(Boolean(Infinity)); // true
console.log(Boolean(-Infinity)); // true

// Falsy Values 
console.log(Boolean(0));         // false
console.log(Boolean(-0));        // false
console.log(Boolean(NaN));       // false
console.log(Boolean(''));        // false
console.log(Boolean(undefined)); // false
console.log(Boolean(null));      // false
